# Part 5: Interactive Visual Analytics with Folium

The launch success rate may depend on many factors such as payload mass, orbit type, and so on. It may also depend on the location and proximities of a launch site, i.e., the initial position of rocket trajectories. Finding an optimal location for building a launch site certainly involves many factors and we aim to discover some of the factors by analyzing the existing launch site locations.

In the previous parts, we have visualized the SpaceX launch dataset using `matplotlib` and `seaborn` and discovered some preliminary correlations between the launch site and success rates. In this part, we will be performing more interactive visual analytics using `Folium`.

`Folium` is a Python library used for creating interactive maps, which can be customized with markers, popups, and various map layers, making it ideal for visualizing geospatial data. This allows us to better understand the geographic distribution of launch sites and examine factors such as proximity to specific locations, terrain, and regional infrastructure. By leveraging Folium, we can explore how the launch sites' locations might influence the success rate of SpaceX launches, adding a spatial dimension to our analysis.

Note: You may need to download the notebook to interact with the maps.

For more about `Folium` https://folium.readthedocs.io/en/latest/

## Part 5: Objectives

*  Mark all launch sites on a map
*  Mark the success/failed launches for each site on the map
*  Calculate the distances between a launch site to its proximities

Let's first import the required Python packages:

In [2]:
import folium
import pandas as pd

In [3]:
from folium.plugins import MarkerCluster
from folium.plugins import MousePosition
from folium.features import DivIcon

First, let's try to add each site's location on a map using site's latitude and longitude coordinates

Now, we will load the dataset

In [4]:
spacex_df = pd.read_csv("spacex_launch_geo.csv")

Now, you can take a look at what are the coordinates for each site.

In [5]:
spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class']]
launch_sites_df = spacex_df.groupby(['Launch Site'], as_index=False).first()
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]
launch_sites_df

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610745

These are the coordiantes for the launch sites. We will use them to build our interactive map.

In [9]:
CCAFS_LC_40_co=[28.562302,-80.577356]
CCAFS_SLC_40_co=[28.563197,-80.576820]
KSC_LC_39A_co=[28.573255, -80.646895]
VAFB_SLC_4E_co=[34.632834, -120.610745]

We first need to create a folium `Map` object, with an initial center location to be NASA Johnson Space Center at Houston, Texas.

In [6]:
nasa_coordinate = [29.559684888503615, -95.0830971930759]
site_map = folium.Map(location=nasa_coordinate, zoom_start=10)

We could use `folium.Circle` to add a highlighted circle area with a text label on a specific coordinate.

In [7]:
circle = folium.Circle(nasa_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('NASA Johnson Space Center'))
marker = folium.map.Marker(
    nasa_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'NASA JSC',
        )
    )
site_map.add_child(circle)
site_map.add_child(marker)

Now, let's add a circle for each launch site in data frame `launch_sites`

In [13]:
# Initial the map
site_map = folium.Map(location=nasa_coordinate, zoom_start=5)
# For each launch site, We can add a Circle object based on its coordinate (Lat, Long) values. In addition, we will add Launch site name as a popup label
CCAFS_LC_40_co=[28.562302,-80.577356]
CCAFS_SLC_40_co=[28.563197,-80.576820]
KSC_LC_39A_co=[28.573255, -80.646895]
VAFB_SLC_4E_co=[34.632834, -120.610745]


folium.Circle(CCAFS_LC_40_co, radius=1000, color='blue', fill=True).add_child(folium.Popup("CCAFS_LC_40_co")).add_to(site_map)
folium.Circle(CCAFS_SLC_40_co, radius=1000, color='blue', fill=True).add_child(folium.Popup("CCAFS_SLC_40_co")).add_to(site_map)
folium.Circle(KSC_LC_39A_co, radius=1000, color='blue', fill=True).add_child(folium.Popup("KSC_LC_39A_co")).add_to(site_map)
folium.Circle(VAFB_SLC_4E_co, radius=1000, color='blue', fill=True).add_child(folium.Popup("VAFB_SLC_4E_co")).add_to(site_map)
folium.map.Marker(CCAFS_LC_40_co, icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'CCAFS_LC_40', )).add_to(site_map)
folium.map.Marker(CCAFS_SLC_40_co, icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'CCAFS_SLC_40', )).add_to(site_map)
folium.map.Marker(KSC_LC_39A_co, icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'KSC_LC_39A', )).add_to(site_map)
folium.map.Marker(VAFB_SLC_4E_co, icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'VAFB_SLC_4E', )).add_to(site_map)
site_map

Now, you can explore the map by zoom-in/out the marked areas
, while trying to answer the following questions:

*   Are all launch sites in proximity to the Equator line?
*   Are all launch sites in very close proximity to the coast?

Next, let's try to enhance the map by adding the launch outcomes for each site, and see which sites have high success rates.
In the dataset spacex_df it has detailed launch records, and the `class` column indicates if this launch was successful or not

In [17]:
spacex_df.tail(10)

     Launch Site        Lat       Long  class marker_color
46    KSC LC-39A  28.573255 -80.646895      1         None
47    KSC LC-39A  28.573255 -80.646895      1         None
48    KSC LC-39A  28.573255 -80.646895      1         None
49  CCAFS SLC-40  28.563197 -80.576820      1         None
50  CCAFS SLC-40  28.563197 -80.576820      1         None
51  CCAFS SLC-40  28.563197 -80.576820      0         None
52  CCAFS SLC-40  28.563197 -80.576820      0         None
53  CCAFS SLC-40  28.563197 -80.576820      0         None
54  CCAFS SLC-40  28.563197 -80.576820      1         None
55  CCAFS SLC-40  28.563197 -80.576820      0         None

Next, let's create markers for all launch records.
If a launch was successful `(class=1)`, then we use a green marker and if a launch was failed, we use a red marker `(class=0)`

Since a launch only happens in one of the four launch sites, which means many launch records will have the exact same coordinate. In `Folium` we can use `Marker clusters` which can be a good way to simplify a map containing many markers having the same coordinate.

Let's first create a `MarkerCluster` object

In [15]:
marker_cluster = MarkerCluster()

Then lets create a new column in `spacex_df` dataframe called `marker_color` to store the marker colors based on the `class` value

In [16]:
spacex_df["marker_color"]=None

In [18]:
def color_function(df):
    if df["class"]==1:
        return "green"
    else:
        return "red"

In [22]:
spacex_df["marker_color"] = spacex_df.apply(color_function, axis=1)

In [23]:
spacex_df.tail(10)

     Launch Site        Lat       Long  class marker_color
46    KSC LC-39A  28.573255 -80.646895      1        green
47    KSC LC-39A  28.573255 -80.646895      1        green
48    KSC LC-39A  28.573255 -80.646895      1        green
49  CCAFS SLC-40  28.563197 -80.576820      1        green
50  CCAFS SLC-40  28.563197 -80.576820      1        green
51  CCAFS SLC-40  28.563197 -80.576820      0          red
52  CCAFS SLC-40  28.563197 -80.576820      0          red
53  CCAFS SLC-40  28.563197 -80.576820      0          red
54  CCAFS SLC-40  28.563197 -80.576820      1        green
55  CCAFS SLC-40  28.563197 -80.576820      0          red

Now, for each launch result in `spacex_df` data frame, we will add a `folium.Marker` to `marker_cluster`

In [24]:
site_map.add_child(marker_cluster)

for index, record in spacex_df.iterrows():
    coordinate = [record['Lat'], record['Long']]
    marker_color = record['marker_color']
    marker_icon = folium.Icon(color='white', icon_color=marker_color)
    marker = folium.Marker(coordinate, icon=marker_icon)
    marker_cluster.add_child(marker)

site_map

Next, we need to explore and analyze the proximities of launch sites.

Let's first add a `MousePosition` on the map to get coordinate for a mouse over a point on the map. As such, while we explore the map, we can easily find the coordinates of any points of interests.

In [26]:
# Add Mouse Position to get the coordinate (Lat, Long) for a mouse over on the map
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

site_map.add_child(mouse_position)
site_map

Now we can zoom in to a launch site and explore its proximity to see if you we can easily find any railway, highway, coastline, etc. we can move the mouse to these points and mark down their coordinates (shown on the top-left) in order to the distance to the launch site.

In [27]:
from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

Now will Mark down a point on the closest coastline using MousePosition and calculate the distance between the coastline point and the launch site.

In [28]:
launch_site_lat = 28.56367
launch_site_lon = -80.57163
coastline_lat = 28.56342  
coastline_lon = -80.56744  
distance_coastline = calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)

In [30]:
distance_coastline

0.410271918104809

In [32]:
costline=[coastline_lat, coastline_lon]

In [34]:
costline

[28.56342, -80.56744]

In [37]:
coordinates = [
    [launch_site_lat, launch_site_lon],
    [coastline_lat, coastline_lon]
]

In [29]:
distance_marker = folium.Marker(
    location=[coastline_lat, coastline_lon],
    icon=DivIcon(
        icon_size=(20, 20),
        icon_anchor=(0, 0),
        html='<div style="font-size: 20; color:#d35400;"><b>%s</b></div>' % "{:10.2f} KM".format(distance_coastline),
    )
)

Now will look for the distance between a launch site to the selected coastline point

In [38]:
lines=folium.PolyLine(locations=coordinates, weight=1)
site_map.add_child(lines)

After exploring the map, we can answer the following questions we present our findings:

*   Are launch sites in close proximity to railways?
*   Are launch sites in close proximity to highways?
*   Are launch sites in close proximity to coastline?
*   Do launch sites keep certain distance away from cities?